[package]
name = "star-ppoprf-ffi"
version = "0.1.0"
authors = ["Ralph Giles <rgiles@brave.com>"]
description = "C API wrapper for the STAR randomness server"
edition = "2018"

[lib]
crate-type = [ "staticlib" ]

[dependencies]
ppoprf = { git = "https://github.com/brave/sta-rs", rev = "9b12fc7508d2105a34c0254281fa51950a4f9ce1" }
curve25519-dalek = "3.2.0"
serde_json = "1.0.80"

[build-dependencies]
cbindgen = "0.20.0"
