[package]
name = "star-randsrv"
version = "0.1.0"
authors = ["Ralph Giles <rgiles@brave.com>"]
description = "Web wrapper for the STAR randomness server"
edition = "2018"

[dependencies]
axum = "0.6.1"
base64 = "0.21.0"
curve25519-dalek = "3.2.0"
ppoprf = { git = "https://github.com/brave/sta-rs", rev = "fe9915741f7b6630" }
serde = "1.0.152"
serde_json = "1.0.85"
tokio = { version = "1.23.0", features = ["full"] }
tower-http = { version = "0.3.5", features = ["trace"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
