[package]
name = "star-ppoprf-ffi"
version = "0.1.0"
authors = ["Ralph Giles <rgiles@brave.com>"]
description = "C API wrapper for the STAR randomness server"
edition = "2018"

[lib]
crate-type = [ "staticlib" ]

[dependencies]
ppoprf = { git = "https://github.com/brave/sta-rs", rev = "6b27875845b9cf5f14e4565021bc453dcf90ee25" }
curve25519-dalek = "3.2.0"
serde_json = "1.0.85"

[build-dependencies]
cbindgen = "0.24.3"
